name: pooptweets

on:
  schedule:
    - cron: '45 19 * * 2-5' #trigger at 1945 UTC on Tues/Wed/Thurs/Fri (30 min after PHESD ottawa scheduled workflow) - https://crontab.guru
  push:
    branches:
      - main

jobs:
  pooptweets-post:
    runs-on: macOS-latest
    env:
      RBOT_TWITTER_API_KEY: ${{ secrets.RBOT_TWITTER_API_KEY }}
      RBOT_TWITTER_API_SECRET: ${{ secrets.RBOT_TWITTER_API_SECRET }}
      RBOT_TWITTER_ACCESS_KEY: ${{ secrets.RBOT_TWITTER_ACCESS_KEY }}
      RBOT_TWITTER_ACCESS_SECRET: ${{ secrets.RBOT_TWITTER_ACCESS_SECRET }}
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v2
      - name: Install rtweet package
        run: Rscript -e 'install.packages("rtweet", dependencies = TRUE)'  
      - name: Create and post tweet
        run: Rscript -e 'install.packages("cowplot", dependencies = TRUE)'
      - name: Install gghighlight package
        run: Rscript -e 'install.packages("gghighlight", dependencies = TRUE)'
      - name: Install tidyverse package
        run: Rscript -e 'install.packages("tidyverse", dependencies = TRUE)'
      - name: Install dplyr package
        run: Rscript -e 'install.packages("dplyr", dependencies = TRUE)'
      - name: Install tidyquant package
        run: Rscript -e 'install.packages("tidyquant", dependencies = TRUE)'
      - name: Install ggrepel package
        run: Rscript -e 'install.packages("ggrepel", dependencies = TRUE)'
      - name: Run the R script
        run: Rscript ottawacov2tweet.R
