name: pooptweets

on:
  schedule:
    - cron: '45 19 * * 2-5' #trigger at 1945 UTC on Tues/Wed/Thurs/Fri (30 min after PHESD ottawa scheduled workflow) - https://crontab.guru
  push:
    branches:
      - main 

jobs:
  pooptweets-post:
    runs-on: macOS-11
    env:
      RBOT_TWITTER_API_KEY: ${{ secrets.RBOT_TWITTER_API_KEY }}
      RBOT_TWITTER_API_SECRET: ${{ secrets.RBOT_TWITTER_API_SECRET }}
      RBOT_TWITTER_ACCESS_KEY: ${{ secrets.RBOT_TWITTER_ACCESS_KEY }}
      RBOT_TWITTER_ACCESS_SECRET: ${{ secrets.RBOT_TWITTER_ACCESS_SECRET }}
    steps:
      - uses: actions/checkout@v2
      - name: Create cache directory
        run: mkdir -p ~/.cache/R
      - name: Cache R package dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/R
          key: ${{ runner.os }}-r-${{ hashFiles('**/lockfile') }}
          restore-keys: |
            ${{ runner.os }}-r-
      - uses: r-lib/actions/setup-r@v2
      - name: Install R packages
        run: |
          Rscript -e 'install.packages(c("rtweet", "cowplot", "gghighlight", "tidyverse", "dplyr", "zoo", "ggrepel", "knitr", "ggplot2"), dependencies = TRUE)'
          Rscript -e 'remotes::install_github("github_username/github_repository")'
    - name: Run the R script
        run: Rscript ottawacov2tweet.R
