name: pooptweets

on:
  schedule:
    - cron: '45 19 * * 2-5' #trigger at 1945 UTC on Tues/Wed/Thurs/Fri (30 minutes after PHESD ottawa scheduled workflow) - https://crontab.guru
#  push:
#    branches:
#      - main

jobs:
  pooptweets-post:
    runs-on: macOS-latest
    env:
      RBOT_TWITTER_API_KEY: ${{ secrets.RBOT_TWITTER_API_KEY }}
      RBOT_TWITTER_API_SECRET: ${{ secrets.RBOT_TWITTER_API_SECRET }}
      RBOT_TWITTER_ACCESS_KEY: ${{ secrets.RBOT_TWITTER_ACCESS_KEY }}
      RBOT_TWITTER_ACCESS_SECRET: ${{ secrets.RBOT_TWITTER_ACCESS_SECRET }}
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v2
      - name: Install R packages
        run: |
          R -e 'install.packages("tools", dependencies = TRUE)'
          R -e 'install.packages("rtweet", dependencies = TRUE)'  
          R -e 'install.packages("cowplot", dependencies = TRUE)'
          R -e 'install.packages("gghighlight", dependencies = TRUE)'
          R -e 'install.packages("tidyverse", dependencies = TRUE)'
          R -e 'install.packages("dplyr", dependencies = TRUE)'
          R -e 'install.packages("tidyquant", dependencies = TRUE)'
          R -e 'install.packages("ggrepel", dependencies = TRUE)'
      - name: Run the plot and tweet generator in R
        run: Rscript checkforupdate.R
      - name: Run the plot and tweet generator in R
        run: Rscript ottawacov2tweet.R
