name: pooptweets

on:
  schedule:
    - cron: '0,30 * * * *'  # trigger at 05:00 every day

jobs:
  pooptweets-post:
    runs-on: macOS-latest
    env:
      TWITTER_CONSUMER_API_KEY: ${{ secrets.TWITTER_CONSUMER_API_KEY }}
      TWITTER_CONSUMER_API_SECRET: ${{ secrets.TWITTER_CONSUMER_API_SECRET }}
      TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
      TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v2
      - name: Install rtweet package
        run: Rscript -e 'install.packages("rtweet", dependencies = TRUE)'  
      - name: Create and post tweet
        run: Rscript -e 'install.packages("cowplot", dependencies = TRUE)'
      - name: Install gghighlight package
        run: Rscript -e 'install.packages("gghighlight", dependencies = TRUE)'
      - name: Install tidyverse package
        run: Rscript -e 'install.packages("tidyverse", dependencies = TRUE)'
      - name: Install dplyr package
        run: Rscript -e 'install.packages("dplyr", dependencies = TRUE)'
      - name: Install tidyquant package
        run: Rscript -e 'install.packages("tidyquant", dependencies = TRUE)'
      - name: Install ggrepel package
        run: Rscript -e 'install.packages("ggrepel", dependencies = TRUE)
        run: Rscript ottawacov2tweet.R
