name: pooptweets

on:
  schedule:
    - cron: '45 19 * * 2-5' #trigger at 1945 UTC on Tues/Wed/Thurs/Fri (30 min after PHESD ottawa scheduled workflow) - https://crontab.guru
  workflow_dispatch:

jobs:
  check-for-update:
    runs-on: macOS-latest
    steps:
    - name: check PHESD repo
      uses: actions/checkout@v2
      with: 
        repository: 'Delatolla-lab/PHESD' #public PHED repo

    - name: Fetch latest commit hash
      id: get_latest_commit
      run: echo "::set-output name=commit::$(git rev-parse HEAD)"

    - name: Load previous commit hash from file (if it exists)
      id: load_previous_commit
      run: |
        if [ -f .prev_commit ]; then 
          echo "::set-output name=prev_commit::$(cat .prev_commit)"
        else
          echo "::set-output name=prev_commit::none"
        fi

    - name: Compare commits
      id: compare_commits
      run: |
        if [ "${{ steps.get_latest_commit.outputs.commit }}" != "${{ steps.load_previous_commit.outputs.prev_commit }}" ]; then
          echo "::set-output name=updated::true"
        else
          echo "::set-output name=updated::false"
        fi
        
    - name: Save latest commit hash to file
      run: echo "${{ steps.get_latest_commit.outputs.commit }}" > .prev_commit

  pooptweets-post:
    needs: check-for-update
    if: needs.check-for-update.outputs.updated == 'true'
    runs-on: macOS-latest
    env:
      RBOT_TWITTER_API_KEY: ${{ secrets.RBOT_TWITTER_API_KEY }}
      RBOT_TWITTER_API_SECRET: ${{ secrets.RBOT_TWITTER_API_SECRET }}
      RBOT_TWITTER_ACCESS_KEY: ${{ secrets.RBOT_TWITTER_ACCESS_KEY }}
      RBOT_TWITTER_ACCESS_SECRET: ${{ secrets.RBOT_TWITTER_ACCESS_SECRET }}
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }} #needed for remotes access
    steps:
      - uses: actions/checkout@v2
      - name: Create cache directory
        run: mkdir -p ~/.cache/R
      - name: Cache R package dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/R
          key: ${{ runner.os }}-r-${{ hashFiles('**/lockfile') }}
          restore-keys: |
            ${{ runner.os }}-r-
      - uses: r-lib/actions/setup-r@v2
      - name: Install R packages
        run: |
          Rscript -e 'install.packages(c("rtweet", "cowplot", "gghighlight", "tidyverse", "tidyquant", "dplyr", "zoo", "ggrepel", "ggplot2"), dependencies = TRUE)'
          Rscript -e 'remotes::install_github("rnaguru/ern")'
      - name: Run the R script
        run: Rscript ottawacov2tweet.R
